### ISSUE TITLE
Gamepad output becomes frozen when switching profiles via Wootlity

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#8] opened 2019-12-16 02:41 UTC
# Wootility Version
3.3.3

# Firmware Version
1.27.3

# Keyboard type
Wooting One

# Issue description
Holding down gamepad keys or thumbstick's while switching to the 'Digital Profile' gets them in a stuck state until you switch back to one of the 'Analog Profile'

> Note: This only occurs via Wootility. Not via the Mode key on the Wooting keyboard.

# Steps to reproduce
1. Open Wootility
2. Create an analog profile and and bind the gamepad to the keyboard similar to the picture below
![cZIX9A90pH](https://user-images.githubusercontent.com/2780639/70874867-5773c280-1fb4-11ea-95b8-9bd4f020a5f4.png)
3. Save the profile
4. Open a [gamepad tester/debugger](https://html5gamepad.com/)
5. Hold down one or more keys that you have bound to the gamepad
6. Use your mouse to click and switch back to the 'Digital Profile'
7. Release the keys
8. Notice that the analog and/or gamepad output is stuck

# Pictures / Video of problem
**(Click for video controls)**
[![Click for link to imgur](https://user-images.githubusercontent.com/2780639/70875019-d79a2800-1fb4-11ea-8298-1e619cbbb3b0.gif)](https://i.imgur.com/8jIUEc1.mp4)

#### Result:
![xmqUL0rg4t](https://user-images.githubusercontent.com/2780639/70875303-cdc4f480-1fb5-11ea-97ae-0b8a3cf19527.png)

**Comment by Rocky04** [comment] 2020-01-05 00:59
**Another very old Bug not related to just analog, the problem is the same for all inputs.** So the problem occur too for the digital keys.

A possible fix should be quiet easy, on every profile switch the all key keys on the used analog interface and the keyboard interfaces should send to zero, only the special modifier states (like caps lock, num lock & scroll lock) should still hold their state. *Depending how the implementation is working it's maybe possible to call the handling just with zero values.*

**Comment by PastaJ36** [comment] 2020-01-31 16:10
Alright, verified this issue. In most cases it was resetting correctly, but there's one more case where the key sticks. If you press a normal key in analog mode and then switch to another analog profile with digital keys off it will stick.

I've changed switching logic now to (pseudocode):
```
if ( targetProfileIsDigital) {
    resetAnalogInterface()
} else if (targetProfileIsAnalog && digitalOff) {
    resetNormalKeys()
}
```

This way digital keys keep state while switching between profiles, but will send zeroes if the profile's digital keys is off. Thoughts?

**Comment by Rocky04** [comment] 2020-01-31 16:24
There are still problems, like if you switch from XInput to DirectInput because these are different interfaces.

if (get_target_profile_digital() == disabled)
{
	resetNormalKeys();
}

```
if (get_target_profile_analog_mode() != current_analog_mode)
{
	reset_cuurent_analog_interface();
}
```

**Comment by PastaJ36** [comment] 2020-02-01 11:51
Yes true, I'll see if I can add it.

**Comment by PastaJ36** [comment] 2020-02-03 13:34
Alright, done now. Will be added to full programmability beta. Thanks

**Comment by PastaJ36** [comment] 2020-05-31 14:18
Keeping this open until the fix is in public

**Closed** 2020-06-17 13:28 UTC
Labels: bug, firmware, resolved
