### ISSUE TITLE
Linux: Stacktrace and undetected in Wootility

### ISSUE THREAD

**Issue by Mushoz** [WootingKb/wootility-issues#99] opened 2021-04-27 08:15 UTC
**Describe the bug**
My Wooting one is resulting in a stack trace under Linux at every boot. The keyboard itself works fine as a regular keyboard, however, I am unable to access any of its features since Wootility does not detect the keyboard. Stack trace:

```
[    7.499375] usb 5-4: Product: WootingOne
[    7.499376] usb 5-4: Manufacturer: Wooting
[    7.499377] usb 5-4: SerialNumber: WOOT_001_A01B1910W011H01666
[    7.512387] usb 1-5: New USB device found, idVendor=0951, idProduct=16a4, bcdDevice= 0.30
[    7.512391] usb 1-5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    7.512393] usb 1-5: Product: HyperX Virtual Surround Sound
[    7.512394] usb 1-5: Manufacturer: Kingston
[    7.512395] usb 1-5: SerialNumber: 00000000
[    7.634286] input: Kingston HyperX Virtual Surround Sound Consumer Control as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-5/1-5:1.3/0003:0951:16A4.000A/input/input17
[    7.668636] hid-generic 0003:03EB:FF01.000B: offset (0) exceeds report_count (0)
[    7.668694] ------------[ cut here ]------------
[    7.668695] WARNING: CPU: 1 PID: 25 at mm/page_alloc.c:4984 __alloc_pages_nodemask+0x308/0x340
[    7.668699] Modules linked in: usbhid dm_crypt cbc encrypted_keys trusted tpm dm_mod crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel aesni_intel crypto_simd cryptd glue_helper ccp rng_core xhci_pci xhci_pci_renesas amdgpu drm_ttm_helper ttm gpu_sched i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops cec drm agpgart
[    7.668714] CPU: 1 PID: 25 Comm: kworker/1:0 Not tainted 5.11.16-arch1-1 #1
[    7.668715] Hardware name: Micro-Star International Co., Ltd. MS-7C91/MAG B550 TOMAHAWK (MS-7C91), BIOS A.50 01/15/2021
[    7.668717] Workqueue: usb_hub_wq hub_event
[    7.668720] RIP: 0010:__alloc_pages_nodemask+0x308/0x340
[    7.668721] Code: ee a9 00 00 0c 00 75 29 48 8d 54 24 10 44 89 ee 44 89 f7 c6 44 24 30 00 48 89 5c 24 18 e8 30 f0 ff ff 49 89 c4 e9 9b fe ff ff <0f> 0b e9 08 ff ff ff 41 80 e6 3f a9 00 00 08 00 75 cc 41 89 ee 41
[    7.668723] RSP: 0018:ffffb1eb402af580 EFLAGS: 00010046
[    7.668724] RAX: 0000000000000000 RBX: 0000000000000a20 RCX: 0000000000000000
[    7.668725] RDX: 0000000000000000 RSI: 0000000000000012 RDI: 0000000000040a20
[    7.668725] RBP: 0000000000000000 R08: 0000000000000000 R09: ffffb1eb402af3d0
[    7.668726] R10: ffffb1eb402af3c8 R11: ffff9aac9f2a90a8 R12: 0000000000000a20
[    7.668727] R13: 0000000000000012 R14: 0000000020000007 R15: ffff9aa1912c9000
[    7.668728] FS:  0000000000000000(0000) GS:ffff9aac6e840000(0000) knlGS:0000000000000000
[    7.668728] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    7.668729] CR2: 00007f65228d1730 CR3: 0000000112a80000 CR4: 0000000000750ee0
[    7.668730] PKRU: 55555554
[    7.668731] Call Trace:
[    7.668734]  kmalloc_order+0x29/0x90
[    7.668737]  kmalloc_order_trace+0x19/0x90
[    7.668738]  __kmalloc+0x27f/0x2e0
[    7.668741]  __usbhid_submit_report+0x89/0x300 [usbhid]
[    7.668744]  usbhid_start+0x6a4/0x750 [usbhid]
[    7.668747]  hid_hw_start+0x21/0x60
[    7.668749]  hid_device_probe+0x106/0x170
[    7.668750]  really_probe+0xf2/0x440
[    7.668753]  driver_probe_device+0xe1/0x150
[    7.668754]  ? driver_allows_async_probing+0x50/0x50
[    7.668755]  bus_for_each_drv+0x8f/0xd0
[    7.668758]  __device_attach+0xe9/0x1e0
[    7.668759]  bus_probe_device+0x8e/0xa0
[    7.668760]  device_add+0x39e/0x850
[    7.668763]  ? __debugfs_create_file+0x110/0x1a0
[    7.668766]  hid_add_device+0xed/0x250
[    7.668767]  usbhid_probe+0x351/0x480 [usbhid]
[    7.668769]  usb_probe_interface+0xe2/0x2a0
[    7.668772]  really_probe+0xf2/0x440
[    7.668773]  driver_probe_device+0xe1/0x150
[    7.668774]  ? driver_allows_async_probing+0x50/0x50
[    7.668775]  bus_for_each_drv+0x8f/0xd0
[    7.668776]  __device_attach+0xe9/0x1e0
[    7.668777]  bus_probe_device+0x8e/0xa0
[    7.668778]  device_add+0x39e/0x850
[    7.668780]  ? usb_create_ep_devs+0x77/0xd0
[    7.668781]  usb_set_configuration+0x46d/0x830
[    7.668783]  usb_generic_driver_probe+0x4c/0x70
[    7.668785]  usb_probe_device+0x39/0xf0
[    7.668786]  really_probe+0xf2/0x440
[    7.668787]  driver_probe_device+0xe1/0x150
[    7.668788]  ? driver_allows_async_probing+0x50/0x50
[    7.668789]  bus_for_each_drv+0x8f/0xd0
[    7.668790]  __device_attach+0xe9/0x1e0
[    7.668791]  bus_probe_device+0x8e/0xa0
[    7.668792]  device_add+0x39e/0x850
[    7.668794]  usb_new_device.cold+0x111/0x2d3
[    7.668797]  hub_event+0xeb6/0x18b0
[    7.668798]  process_one_work+0x214/0x3e0
[    7.668801]  worker_thread+0x4d/0x3d0
[    7.668802]  ? rescuer_thread+0x3c0/0x3c0
[    7.668803]  kthread+0x133/0x150
[    7.668804]  ? __kthread_bind_mask+0x60/0x60
[    7.668806]  ret_from_fork+0x22/0x30
[    7.668809] ---[ end trace cca7ef68a212c002 ]---
[    7.668810] hid-generic 0003:03EB:FF01.000B: control queueing failed
[    7.668831] hid-generic 0003:03EB:FF01.000B: No inputs registered, leaving
[    7.668922] hid-generic 0003:03EB:FF01.000B: hidraw9: USB HID v1.11 Keyboard [Wooting WootingOne] on usb-0000:2f:00.3-4/input1
[    7.676623] hid-generic 0003:03EB:FF01.000C: hiddev99,hidraw10: USB HID v1.11 Device [Wooting WootingOne] on usb-0000:2f:00.3-4/input2
[    7.684517] input: Wooting WootingOne as /devices/pci0000:00/0000:00:08.1/0000:2f:00.3/usb5/5-4/5-4:1.3/0003:03EB:FF01.000D/input/input20
[    7.690703] input: Kingston HyperX Virtual Surround Sound as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-5/1-5:1.3/0003:0951:16A4.000A/input/input18
[    7.690776] hid-generic 0003:0951:16A4.000A: input,hiddev100,hidraw11: USB HID v1.11 Device [Kingston HyperX Virtual Surround Sound] on usb-0000:02:00.0-5/input3
[    7.747561] hid-generic 0003:03EB:FF01.000D: input,hidraw12: USB HID v1.11 Keyboard [Wooting WootingOne] on usb-0000:2f:00.3-4/input3
[    7.772632] input: Wooting WootingOne System Control as /devices/pci0000:00/0000:00:08.1/0000:2f:00.3/usb5/5-4/5-4:1.4/0003:03EB:FF01.000E/input/input21
[    7.814105] usb 1-8: new full-speed USB device number 4 using xhci_hcd
[    7.827546] input: Wooting WootingOne Consumer Control as /devices/pci0000:00/0000:00:08.1/0000:2f:00.3/usb5/5-4/5-4:1.4/0003:03EB:FF01.000E/input/input22
[    7.827593] hid-generic 0003:03EB:FF01.000E: input,hidraw13: USB HID v1.11 Device [Wooting WootingOne] on usb-0000:2f:00.3-4/input4
[    7.855632] hid-generic 0003:03EB:FF01.000F: hiddev101,hidraw14: USB HID v1.11 Device [Wooting WootingOne] on usb-0000:2f:00.3-4/input5
[    7.887326] usbhid 5-4:1.6: can't add hid device: -32
[    7.887366] usbhid: probe of 5-4:1.6 failed with error -32
```

**To Reproduce**
Boot into Linux with the keyboard connected. Look in your dmesg log.

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.11.16 Kernel
 - If USB problem: MSI B550 Tomahawk + 5900x 

**Wootility and Firmware version**
Wootility: 3.6.15
Keyboard firmware: Unsure, keyboard is not detected

**Keyboard Type**
Wooting one

**Comment by kleisauke** [comment] 2021-04-28 12:27
Probably a duplicate of https://github.com/WootingKb/wootility-issues/issues/29. I've the same issue with my Wooting two keyboard (firmware version 1.30.12) running on Fedora 34.
<details>
  <summary>Details</summary>

```
[    1.799247] usb 1-10: new full-speed USB device number 4 using xhci_hcd
[    1.927543] usb 1-10: New USB device found, idVendor=03eb, idProduct=ff02, bcdDevice= 0.94
[    1.927545] usb 1-10: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.927546] usb 1-10: Product: WootingTwo
[    1.927547] usb 1-10: Manufacturer: Wooting
[    1.927547] usb 1-10: SerialNumber: WOOT_002_A01B1932W021H00186
[    1.930487] hid-generic 0003:03EB:FF02.0003: hiddev97,hidraw2: USB HID v1.11 Device [Wooting WootingTwo] on usb-0000:00:14.0-10/input0
[    1.930938] hid-generic 0003:03EB:FF02.0004: offset (0) exceeds report_count (0)
[    1.930942] ------------[ cut here ]------------
[    1.930942] WARNING: CPU: 2 PID: 151 at mm/page_alloc.c:4984 __alloc_pages_nodemask+0x2b8/0x340
[    1.930947] Modules linked in: mxm_wmi crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel nvme nvme_core r8169 wmi video fuse
[    1.930953] CPU: 2 PID: 151 Comm: kworker/2:2 Not tainted 5.11.15-300.fc34.x86_64 #1
[    1.930954] Hardware name: Micro-Star International Co., Ltd. MS-7B48/Z370-A PRO (MS-7B48), BIOS 2.90 04/02/2019
[    1.930955] Workqueue: usb_hub_wq hub_event
[    1.930958] RIP: 0010:__alloc_pages_nodemask+0x2b8/0x340
[    1.930960] Code: 63 fe ff ff 89 e8 44 89 fa c1 e8 03 80 ca 80 83 e0 03 83 f8 01 44 0f 44 fa e9 49 fe ff ff 81 e5 00 20 00 00 0f 85 32 ff ff ff <0f> 0b e9 2b ff ff ff 0f 0b 0f 0b e9 d4 fd ff ff 31 c0 e9 e3 fd ff
[    1.930961] RSP: 0000:ffffbcc4c0387618 EFLAGS: 00010046
[    1.930962] RAX: 0000000000000000 RBX: 0000000000000a20 RCX: 0000000000000000
[    1.930963] RDX: 0000000000000000 RSI: 0000000000000012 RDI: 0000000000040a20
[    1.930964] RBP: 0000000000000000 R08: 0000000000000000 R09: ffffbcc4c0387400
[    1.930965] R10: ffffbcc4c03873f8 R11: ffffffffb5b44f08 R12: 0000000000000000
[    1.930966] R13: 0000000000000012 R14: 0000000020000007 R15: ffff9f3749737000
[    1.930967] FS:  0000000000000000(0000) GS:ffff9f3e8ec80000(0000) knlGS:0000000000000000
[    1.930968] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    1.930969] CR2: 00007efc20003000 CR3: 0000000100bba004 CR4: 00000000003706e0
[    1.930970] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    1.930970] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[    1.930971] Call Trace:
[    1.930973]  kmalloc_order+0x29/0x90
[    1.930975]  kmalloc_order_trace+0x19/0x80
[    1.930977]  __usbhid_submit_report+0x89/0x300
[    1.930979]  usbhid_start+0x6a0/0x740
[    1.930981]  hid_hw_start+0x21/0x60
[    1.930983]  hid_device_probe+0x106/0x170
[    1.930984]  really_probe+0xf2/0x440
[    1.930987]  driver_probe_device+0xe1/0x150
[    1.930988]  ? driver_allows_async_probing+0x50/0x50
[    1.930990]  bus_for_each_drv+0x6a/0xa0
[    1.930992]  __device_attach+0xb4/0x1b0
[    1.930994]  bus_probe_device+0x8e/0xa0
[    1.930995]  device_add+0x39e/0x850
[    1.930997]  ? __debugfs_create_file+0x113/0x1a0
[    1.930999]  hid_add_device+0xd9/0x210
[    1.931001]  usbhid_probe+0x350/0x480
[    1.931002]  usb_probe_interface+0xe2/0x2a0
[    1.931004]  really_probe+0xf2/0x440
[    1.931005]  driver_probe_device+0xe1/0x150
[    1.931007]  ? driver_allows_async_probing+0x50/0x50
[    1.931009]  bus_for_each_drv+0x6a/0xa0
[    1.931010]  __device_attach+0xb4/0x1b0
[    1.931012]  bus_probe_device+0x8e/0xa0
[    1.931013]  device_add+0x39e/0x850
[    1.931014]  ? usb_create_ep_devs+0x77/0xd0
[    1.931016]  usb_set_configuration+0x46b/0x830
[    1.931019]  usb_generic_driver_probe+0x4c/0x70
[    1.931021]  usb_probe_device+0x39/0x100
[    1.931023]  really_probe+0xf2/0x440
[    1.931024]  driver_probe_device+0xe1/0x150
[    1.931026]  ? driver_allows_async_probing+0x50/0x50
[    1.931027]  bus_for_each_drv+0x6a/0xa0
[    1.931029]  __device_attach+0xb4/0x1b0
[    1.931031]  bus_probe_device+0x8e/0xa0
[    1.931032]  device_add+0x39e/0x850
[    1.931033]  ? _dev_info+0x5c/0x5e
[    1.931035]  usb_new_device.cold+0x10f/0x2d0
[    1.931037]  hub_event+0x13ed/0x1760
[    1.931039]  process_one_work+0x1ec/0x380
[    1.931041]  worker_thread+0x53/0x3e0
[    1.931042]  ? process_one_work+0x380/0x380
[    1.931043]  kthread+0x11b/0x140
[    1.931045]  ? kthread_associate_blkcg+0xa0/0xa0
[    1.931047]  ret_from_fork+0x22/0x30
[    1.931051] ---[ end trace a2eb7abd13e357ab ]---
[    1.931052] hid-generic 0003:03EB:FF02.0004: control queueing failed
[    1.931066] hid-generic 0003:03EB:FF02.0004: No inputs registered, leaving
[    1.931115] hid-generic 0003:03EB:FF02.0004: hidraw3: USB HID v1.11 Keyboard [Wooting WootingTwo] on usb-0000:00:14.0-10/input1
[    1.932141] hid-generic 0003:03EB:FF02.0005: hiddev98,hidraw4: USB HID v1.11 Device [Wooting WootingTwo] on usb-0000:00:14.0-10/input2
[    1.932764] input: Wooting WootingTwo as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.3/0003:03EB:FF02.0006/input/input7
[    1.984398] hid-generic 0003:03EB:FF02.0006: input,hidraw5: USB HID v1.11 Keyboard [Wooting WootingTwo] on usb-0000:00:14.0-10/input3
[    1.984909] input: Wooting WootingTwo System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.4/0003:03EB:FF02.0007/input/input8
[    2.036309] input: Wooting WootingTwo Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10:1.4/0003:03EB:FF02.0007/input/input9
[    2.036415] hid-generic 0003:03EB:FF02.0007: input,hidraw6: USB HID v1.11 Device [Wooting WootingTwo] on usb-0000:00:14.0-10/input4
[    2.036963] hid-generic 0003:03EB:FF02.0008: hiddev99,hidraw7: USB HID v1.11 Device [Wooting WootingTwo] on usb-0000:00:14.0-10/input5
[    2.037537] hid-generic 0003:03EB:FF02.0009: hiddev100,hidraw8: USB HID v1.11 Device [Wooting WootingTwo] on usb-0000:00:14.0-10/input6
```
</details>

> I am unable to access any of its features since Wootility does not detect the keyboard

Wootility must be started with higher privileges (e.g. with sudo) or the user needs additional permissions to access the device. See:
https://wooting.helpscoutdocs.com/article/68-wootility-configuring-device-access-for-wootility-under-linux-udev-rules

**Comment by simon-wh** [comment] 2021-06-16 09:27
As mentioned above this does appear to be a duplicate of #29. This in itself has no effect on the usability of the keyboard under Linux. For getting it properly detected in Wootility under Linux see @kleisauke's suggestion

**Closed by simon-wh** 2021-06-16 09:27 UTC
