### ISSUE TITLE
Wooting 60he space bar double clicking with rgb sleep mode toggled off 

### ISSUE THREAD

**Issue by pnegus** [WootingKb/wootility-issues#214] opened 2023-05-20 02:00 UTC
This is a bit of a bizarre issue, but I've tested this multiple times. The issue appears to be only present with the space bar, though I haven't tested other keys extensively.

When RGB sleep mode under settings > keyboard settings is toggled off, and Tachyon mode is enabled, testing the space bar produces lots of double clicks. This occurs whether RGB is enabled or not: 

List of settings: 

- Rapid trigger enabled (.3mm)
- actuation point set to .3mm global.
- RGB off/on
- Gamepad disabled
- Tachyon mode enabled

EDIT: further testing shows that the double clicks occur only when the FIRST PROFILE (typing) is enabled. No double clicks are observed when using the RAPID profile with all the settings above enabled. Also, this issue seems exclusive to tachyon mode.

![image](https://github.com/WootingKb/wootility-issues/assets/51723374/f4213b63-b6a4-467b-b55f-99a1c342e6b4)

The double clicks appear to occur every half a second (at regular intervals), indicating some sort of bug in the firmware.

With RGB sleep mode off, there is no such issue: 

![image](https://github.com/WootingKb/wootility-issues/assets/51723374/775c1729-db17-47c1-b8e9-43c1b78596bc)

**Comment by Rocky04** [comment] 2023-05-20 22:44
We were able to reproduce this issue a few days ago. The issue is limited to the AVR models and don't seem to occur on the ARM models.
_Haven't checked if this also happen on the full size W2 HE._

**Comment by pnegus** [comment] 2023-05-20 23:19
Sounds good. I have an AVR model, forgot to mention that. Tested with the test firmwares 2.16-2.19 including the most recent stable 2.19 and all have the same issue.

**Comment by simon-wh** [comment] 2023-05-22 12:53
Hi, thanks for the report. I've been digging into this since last Friday, is a tricky one, but hopefully I can find the root cause soon.

Could you link the page you used to check for double presses? Might be helpful as the methods I've been using to check if the issue is present are not amazing

**Comment by JustCauseWhyNot** [comment] 2023-05-22 17:34
It's this [sight](https://cps-check.com/double-click-keyboard) I'm 99.9% sure. And I'm also suffering the same issue.

**Comment by simon-wh** [comment] 2023-05-25 15:13
I've gotten to the bottom of this issue, took a lot of time, but got there in the end. I'm now working towards pushing out a firmware build with the fix, it'll be v2.6.20. I'll update this when it's out.

**Comment by simon-wh** [comment] 2023-05-25 15:28
v2.6.20 is now available. I'm going to close the issue now. Post here if you run into it again

**Closed by simon-wh** 2023-05-25 15:28 UTC
