### ISSUE TITLE
Multi-input Analog input not working correctly

### ISSUE THREAD

**Issue by elyasmehtabuddin** [WootingKb/wootility-issues#281] opened 2024-05-11 05:22 UTC
**Description**
The Wootility Gamepad Response -> Analog feature only works with a single direction, when multiple directions are pressed the setting seems to be ignored.

Look at the GIF below.
The analog curve is set to "Instant", so either left stick is pressed 0% or 100%. This works fine when inputting Left stick up, however when inputting left stick up + left stick left I would expect the output to either be either left stick up or 45 degrees topleft because the analog curve is instant. However I can make small angles towards the topleft as I slowly press left stick left.

**GIF**
![problem](https://i.imgur.com/mW98k04.gif)

**Wootility and Firmware version**
Wootility v4.6.18

**Keyboard Type**
Wooting 60HE
Firmware 2.7.2

**Comment by simon-wh** [comment] 2024-05-11 09:02
To achieve the behaviour you seem to want, you need to use the turbo curve. 

The instant curve is for when you always want max output magnitude, but you still want to use the range of the press to adjust the angle. 

The turbo curve removes the range of the press as a factor and will then snap to each primary & diagonal directions

**Comment by simon-wh** [comment] 2024-05-16 09:43
i.e. this is intended behaviour of the configuration you've chosen, so I'm going to close this

**Closed as completed by simon-wh** 2024-05-16 09:43 UTC
Labels: bug
